## NUMPY array and Basics
learn about numpy with FAMILY and friends

In [6]:
import numpy as np

# creating array from list

In [7]:
arr_1d = np.array([1, 2, 3, 4])
print("1D Array: ", arr_1d)

arr_2d = np.array([[5, 6, 8],
                   [0, 9, 7]])
print("2D Array:", arr_2d)

1D Array:  [1 2 3 4]
2D Array: [[5 6 8]
 [0 9 7]]


### List v/s Numpy Array

In [ ]:
py_list = [1, 2, 3]
print("Python List multiplication: ", py_list * 2)

# element wise multiplication
np_array = np.array([6, 7, 8])
print("Python array multiplication: ", np_array * 2)

Python List multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [12 14 16]


In [ ]:
import time
start = time.time() # the 'time.time()' method gives you exact time
py_list = [i*2 for i in range(1000000)] # for loop inside LIST
print("\n List Operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)
print("\n Numpy Operation time: ", time.time() - start)


 List Operation time:  0.10515785217285156

 Numpy Operation time:  0.002513408660888672


### creating arrays from SCRATCH

In [10]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
full = np.full((7, 8), 6)
print("full array: \n", full)

full array: 
 [[6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6]]


In [18]:
random = np.random.random((2, 3))
print("random array: \n", random)

# In python range is always outter exclusive boundary
sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence) 

random array: 
 [[0.74420262 0.58691253 0.91798835]
 [0.99389429 0.77740362 0.68583647]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrices, Tensor

In [26]:
vector = np.array([2, 3, 5])
print("Vector: \n", vector)

matrices = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("Matrix: \n", matrices)

Vector: 
 [2 3 5]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Numpy k tensor mein multi dimensional array hote hain
tensor = np.array([[[1, 2], [3, 4]],
                  [[5, 6],[7, 8]]])
print("TENSOR: \n", tensor)

TENSOR: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [32]:
arr = np.array([[1, 2 ,3],
               [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimensions ", arr.ndim)
print("Size", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimensions  2
Size 6
DType  int64


### ARRAY Reshaping

In [38]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: \n ", reshaped)

flattend = reshaped.flatten()
print("\n Flattend array: ", flattend)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array: \n ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array: 
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
